<a href="https://colab.research.google.com/github/havaledar/ECON3740_F24/blob/main/ECON3740_F24_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logical operations

1. & (AND): Logical AND. Returns True when both conditions are True.
2. | (OR): Logical OR. Returns True when at least one of the conditions is True.
3. ~ (NOT): Logical NOT. Inverts the boolean values (True becomes False and vice versa).

In [3]:
%%capture

!pip install wooldridge

import wooldridge as woo

data = woo.data('401k')

In [4]:
sorted(data['age'].unique())

[4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 48,
 51]

In [5]:
data[data['age'] >= 20]

           prate  mrate  totpart  totelg  age  totemp  sole   ltotemp
4      82.500000   0.53    591.0   716.0   28   933.0     1  6.838405
6     100.000000   0.53    399.0   399.0   31   628.0     1  6.442540
8     100.000000   0.22    234.0   234.0   21   279.0     1  5.631212
11    100.000000   1.11    187.0   187.0   20   237.0     1  5.468060
23    100.000000   0.95    381.0   381.0   23   422.0     0  6.045005
...          ...    ...      ...     ...  ...     ...   ...       ...
1526  100.000000   4.02    432.0   432.0   34   660.0     0  6.492240
1527   89.099998   1.40    212.0   238.0   31   469.0     1  6.150603
1529   85.099998   0.33    553.0   650.0   24   907.0     0  6.810143
1531  100.000000   2.27   1928.0  1928.0   35  2171.0     0  7.682943
1533  100.000000   0.45   2179.0  2179.0   24  3187.0     0  8.066835

[330 rows x 8 columns]

In [8]:
data[(data['age'] >= 20) & (data['age'] <= 30)]

           prate  mrate  totpart   totelg  age   totemp  sole    ltotemp
4      82.500000   0.53    591.0    716.0   28    933.0     1   6.838405
8     100.000000   0.22    234.0    234.0   21    279.0     1   5.631212
11    100.000000   1.11    187.0    187.0   20    237.0     1   5.468060
23    100.000000   0.95    381.0    381.0   23    422.0     0   6.045005
26     88.300003   0.96   3858.0   4371.0   28   4371.0     0   8.382747
...          ...    ...      ...      ...  ...      ...   ...        ...
1505  100.000000   0.78  15923.0  15923.0   26  45000.0     0  10.714417
1506  100.000000   3.10     92.0     92.0   26    108.0     1   4.682131
1522  100.000000   3.24   2477.0   2477.0   30   3523.0     0   8.167068
1529   85.099998   0.33    553.0    650.0   24    907.0     0   6.810143
1533  100.000000   0.45   2179.0   2179.0   24   3187.0     0   8.066835

[218 rows x 8 columns]

In [10]:
data[(data['age'] >= 20) | (data['age'] <= 30)]

           prate  mrate  totpart  totelg  age  totemp  sole   ltotemp
0      26.100000   0.21   1653.0  6322.0    8  8709.0     0  9.072112
1     100.000000   1.42    262.0   262.0    6   315.0     1  5.752573
2      97.599998   0.91    166.0   170.0   10   275.0     1  5.616771
3     100.000000   0.42    257.0   257.0    7   500.0     0  6.214608
4      82.500000   0.53    591.0   716.0   28   933.0     1  6.838405
...          ...    ...      ...     ...  ...     ...   ...       ...
1529   85.099998   0.33    553.0   650.0   24   907.0     0  6.810143
1530  100.000000   2.52    142.0   142.0   17   197.0     1  5.283204
1531  100.000000   2.27   1928.0  1928.0   35  2171.0     0  7.682943
1532  100.000000   0.58    166.0   166.0    8   931.0     1  6.836259
1533  100.000000   0.45   2179.0  2179.0   24  3187.0     0  8.066835

[1534 rows x 8 columns]

# Selecting rows and Columns

In [13]:
data[['mrate', 'prate']]

      mrate       prate
0      0.21   26.100000
1      1.42  100.000000
2      0.91   97.599998
3      0.42  100.000000
4      0.53   82.500000
...     ...         ...
1529   0.33   85.099998
1530   2.52  100.000000
1531   2.27  100.000000
1532   0.58  100.000000
1533   0.45  100.000000

[1534 rows x 2 columns]

In [14]:
data[:50]

         prate  mrate  totpart  totelg  age  totemp  sole   ltotemp
0    26.100000   0.21   1653.0  6322.0    8  8709.0     0  9.072112
1   100.000000   1.42    262.0   262.0    6   315.0     1  5.752573
2    97.599998   0.91    166.0   170.0   10   275.0     1  5.616771
3   100.000000   0.42    257.0   257.0    7   500.0     0  6.214608
4    82.500000   0.53    591.0   716.0   28   933.0     1  6.838405
5   100.000000   1.82     92.0    92.0    7   143.0     1  4.962845
6   100.000000   0.53    399.0   399.0   31   628.0     1  6.442540
7    92.500000   0.34    210.0   227.0   13   823.0     0  6.712956
8   100.000000   0.22    234.0   234.0   21   279.0     1  5.631212
9    96.800003   0.60    120.0   124.0   10   141.0     1  4.948760
10   83.000000   0.50    156.0   188.0    5   252.0     0  5.529429
11  100.000000   1.11    187.0   187.0   20   237.0     1  5.468060
12   65.500000   0.43    350.0   534.0    5   681.0     1  6.523562
13   84.900002   0.51   1519.0  1790.0   10  2557.0     0  7.846590
14  100.000000   0.19    150.0   150.0    7   187.0     1  5.231109
15  100.000000   0.41    160.0   160.0    7   188.0     1  5.236442
16  100.000000   0.84   3448.0  3448.0   13  4120.0     0  8.323608
17   77.599998   0.46    225.0   290.0   15   341.0     0  5.831882
18  100.000000   0.45    519.0   519.0   15   598.0     0  6.393591
19  100.000000   1.13    176.0   176.0    8   273.0     1  5.609472
20   66.900002   0.48     79.0   118.0    5   224.0     1  5.411646
21  100.000000   0.39    270.0   270.0    7   415.0     0  6.028278
22   70.300003   0.21    201.0   286.0    7   361.0     0  5.888878
23  100.000000   0.95    381.0   381.0   23   422.0     0  6.045005
24   51.299999   0.34    284.0   554.0    9   797.0     1  6.680855
25   61.299999   0.36    171.0   279.0   15  2102.0     1  7.650645
26   88.300003   0.96   3858.0  4371.0   28  4371.0     0  8.382747
27  100.000000   0.87    143.0   143.0    8   143.0     1  4.962845
28   82.900002   4.20    107.0   129.0    7   131.0     1  4.875197
29   77.800003   0.08    770.0   990.0    6  1042.0     0  6.948897
30  100.000000   0.91    179.0   179.0    6   312.0     1  5.743003
31   90.099998   0.44   2803.0  3110.0    6  3543.0     0  8.172729
32   85.300003   0.62     93.0   109.0   13   158.0     0  5.062595
33  100.000000   0.28    425.0   425.0    7   458.0     0  6.126869
34  100.000000   0.59   2027.0  2027.0    7  2442.0     0  7.800573
35   75.599998   0.30    438.0   579.0   11  1721.0     0  7.450661
36  100.000000   0.56    584.0   584.0    7   685.0     1  6.529419
37  100.000000   0.65   1284.0  1284.0    5  1559.0     0  7.351800
38  100.000000   1.31    109.0   109.0   37   297.0     1  5.693732
39   78.199997   0.21   1017.0  1301.0    7  2125.0     0  7.661527
40   77.400002   0.41    209.0   270.0    7   381.0     1  5.942800
41  100.000000   0.23    145.0   145.0    6   405.0     0  6.003887
42   77.000000   0.41    612.0   795.0   12  1125.0     0  7.025538
43  100.000000   2.03    133.0   133.0   35   206.0     1  5.327876
44   98.900002   0.52    275.0   278.0   42   297.0     0  5.693732
45   75.300003   0.39    192.0   255.0    6  1024.0     0  6.931472
46   77.199997   0.16    464.0   601.0    6   636.0     0  6.455199
47  100.000000   0.99    542.0   542.0    9   622.0     0  6.432940
48   88.500000   0.10   3107.0  3510.0    5  6428.0     0  8.768418
49  100.000000   0.02    732.0   732.0    7  2284.0     0  7.733684

# Concating dataframes

In [15]:
df20 = data[(data['age'] == 20)]

In [17]:
df30 = data[(data['age'] == 30)]

In [19]:
import pandas as pd
pd.concat([df20, df30])

           prate  mrate  totpart   totelg  age   totemp  sole    ltotemp
11    100.000000   1.11    187.0    187.0   20    237.0     1   5.468060
59    100.000000   1.14    307.0    307.0   20    411.0     1   6.018593
74     73.800003   1.12    357.0    484.0   20  24656.0     1  10.112776
149    81.000000   0.78    328.0    405.0   20    609.0     0   6.411819
170   100.000000   0.21    235.0    235.0   20    768.0     0   6.643790
176    87.599998   0.63     99.0    113.0   20    154.0     1   5.036952
184   100.000000   0.29     65.0     65.0   20    118.0     1   4.770685
237    75.500000   0.24    880.0   1165.0   20   1306.0     0   7.174724
252   100.000000   2.60    132.0    132.0   20    205.0     1   5.323010
290    64.900002   0.42     96.0    148.0   20    225.0     1   5.416101
300   100.000000   0.63    214.0    214.0   20    268.0     0   5.590987
317   100.000000   0.80    547.0    547.0   20    869.0     1   6.767343
473   100.000000   1.54    597.0    597.0   20    642.0     0   6.464588
527    86.099998   0.60    118.0    137.0   20    160.0     0   5.075174
578    80.500000   0.56   1439.0   1788.0   20   2036.0     0   7.618742
602   100.000000   0.96    105.0    105.0   20    154.0     1   5.036952
603    93.900002   1.59   2001.0   2131.0   20   3287.0     1   8.097731
677   100.000000   0.20    123.0    123.0   20    131.0     1   4.875197
727   100.000000   0.47    190.0    190.0   20    197.0     1   5.283204
744   100.000000   0.40    700.0    700.0   20   2872.0     1   7.962764
786   100.000000   0.81    215.0    215.0   20    215.0     0   5.370638
801   100.000000   1.08    243.0    243.0   20    244.0     1   5.497168
841    77.300003   0.15   1395.0   1805.0   20   2375.0     0   7.772753
874    90.099998   0.11    649.0    720.0   20   1733.0     1   7.457609
877    72.500000   0.86   1376.0   1898.0   20   2247.0     0   7.717351
911   100.000000   3.46    100.0    100.0   20    201.0     0   5.303305
945   100.000000   1.07    748.0    748.0   20    931.0     1   6.836259
966    78.800003   1.15    178.0    226.0   20    451.0     1   6.111467
996   100.000000   3.73    105.0    105.0   20    284.0     1   5.648974
1030  100.000000   0.29    322.0    322.0   20    388.0     1   5.961005
1031   82.500000   0.25    950.0   1151.0   20   1567.0     1   7.356918
1091   87.500000   1.00   1633.0   1867.0   20   8686.0     0   9.069468
1170  100.000000   0.97     88.0     88.0   20    284.0     1   5.648974
1383  100.000000   0.72    138.0    138.0   20    157.0     1   5.056246
232    82.599998   0.64    176.0    213.0   30    254.0     0   5.537334
574    84.300003   1.12    118.0    140.0   30    200.0     1   5.298317
699   100.000000   1.03   1610.0   1610.0   30   3680.0     1   8.210668
798    89.599998   0.34    250.0    279.0   30    327.0     1   5.789960
872   100.000000   0.71     92.0     92.0   30    111.0     1   4.709530
999   100.000000   0.15    110.0    110.0   30    182.0     1   5.204007
1016  100.000000   2.16    529.0    529.0   30    680.0     0   6.522093
1057  100.000000   1.27    773.0    773.0   30    923.0     1   6.827629
1246  100.000000   0.24    197.0    197.0   30    450.0     1   6.109248
1291   77.000000   0.44  33430.0  43428.0   30  54497.0     0  10.905901
1356  100.000000   1.30    129.0    129.0   30    236.0     0   5.463832
1522  100.000000   3.24   2477.0   2477.0   30   3523.0     0   8.167068

# if

In [22]:
num = -1

if num > 0:
    print("The number is positive.")

In [24]:
num = -4

if num > 0:
    print("The number is positive.")
else:
    print("The number is not positive.")

The number is not positive.

In [27]:
num = -10

if num > 0:
    print("The number is positive.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is negative.

# for

In [28]:
fruits = ['apple', 'banana', 'cherry']

In [33]:
fruits = ['apple', 'banana', 'cherry']

for f in fruits:
    print(f)

apple
banana
cherry

In [35]:
numbers = [1, 2, 3, 4, 5]
total = 0

for num in numbers:
    total += num
    print(total)

1
3
6
10
15

## range

In [39]:
list(range(1, 6))

[1, 2, 3, 4, 5]

In [40]:
total = 0

for i in range(1,6):
    total += i

print(f"The total sum is {total}")

The total sum is 15

#Google Drive

In [ ]:
# !pip install gdown==v4.6.3
import gdown
import pandas as pd



1.   Upload your file to the Google Drive.
2.   Click **Share** and change the access to **Anyone with the link**.
3. Copy the URL to the file.

![Screenshot 2024-09-27 7.12.07 AM.png]()

In [ ]:
url = 'https://drive.google.com/file/d/1eq0As_rQFayM4d6QR43owoW4huD3urhE/view?usp=sharing'
output_filename = 'file.dta'
gdown.download(url, output_filename, fuzzy=True ,quiet=False)

In [ ]:
pd.read_stata("file.dta")

#URL

In [ ]:
data = pd.read_excel("https://cengage-dps.s3.amazonaws.com/economics/690273_wooldridge_8e/meap01_v4.xlsx")

# Stats Canada

In [ ]:
%%capture
!pip install stats-can

In [ ]:
import stats_can

Total employed, all classes of workers

https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1410028801

In [ ]:
df = stats_can.sc.vectors_to_df('v2066967', periods = 20)

In [ ]:
df.columns = ['Total employed']

df

# Scraping

In [ ]:
url = "https://en.wikipedia.org/wiki/Economy_of_Canada"

## Pandas

In [ ]:
tables = pd.read_html(url)

tables[5]

## BeautifulSoup

In [ ]:
import requests
from bs4 import BeautifulSoup

In [ ]:
# Downloading contents of the web page
data = requests.get(url).text

In [ ]:
# Creating BeautifulSoup object
soup = BeautifulSoup(data, 'html.parser')

In [ ]:
# Verifying tables and their classes
print('Classes of each table:')
for table in soup.find_all('table'):
    print(table.get('class'))

In [ ]:
# Creating list with all tables
tables = soup.find_all('table')

In [ ]:
tables[5]

In [ ]:
columns = [
    'Year',
    'GDP_PPP_Bil_USD',
    'GDP_per_capita_PPP_USD',
    'GDP_nominal_Bil_USD',
    'GDP_per_capita_nominal_USD',
    'GDP_growth_real',
    'Inflation_rate_percent',
    'Unemployment_percent',
    'Government_debt_percent_of_GDP'
]

df = pd.DataFrame(columns=columns)

In [ ]:
for row in tables[5].tbody.find_all('tr'):
    # Find all data for each column
    columns = row.find_all('td')

    if columns != []:
        year = columns[0].text.strip()
        gdp_ppp_bil_usd = columns[1].text.strip()
        gdp_per_capita_ppp_usd = columns[2].text.strip()
        gdp_nominal_bil_usd = columns[3].text.strip()
        gdp_per_capita_nominal_usd = columns[4].text.strip()
        gdp_growth_real = columns[5].text.strip()
        inflation_rate_percent = columns[6].text.strip()
        unemployment_percent = columns[7].text.strip()
        government_debt_percent_of_gdp = columns[8].text.strip()

        row_data = {
            'Year': year,
            'GDP_PPP_Bil_USD': gdp_ppp_bil_usd,
            'GDP_per_capita_PPP_USD': gdp_per_capita_ppp_usd,
            'GDP_nominal_Bil_USD': gdp_nominal_bil_usd,
            'GDP_per_capita_nominal_USD': gdp_per_capita_nominal_usd,
            'GDP_growth_real': gdp_growth_real,
            'Inflation_rate_percent': inflation_rate_percent,
            'Unemployment_percent': unemployment_percent,
            'Government_debt_percent_of_GDP': government_debt_percent_of_gdp
        }

        # Convert row_data to a DataFrame
        row_df = pd.DataFrame([row_data])

        # Use pandas.concat to add the row to the df_short DataFrame
        df = pd.concat([df, row_df], ignore_index=True)

In [ ]:
df.head()