<a href="https://colab.research.google.com/github/havaledar/ECON3740_F24/blob/main/ECON3740_F24_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Google Colab Notebook

## Creating New Notebook



1.   Create a Notebook by cliking on this. https://colab.google/
2.   Use the Notebook shared in the GitHub and save it to your Google Drive.
3.   Click File > New Notebook in Drive.

# Reading Excel file

### Donwload the Excel file

First download the data by clicking on the Open Excel File in MindTap.

![Screenshot from 2024-09-11 17-35-10.png]()

### Import pandas

In [6]:
import pandas as pd

### read_excel


$\color{Red}{\text{Do not use the data from Wooldridge library.}}$

Instead, upload the Excel file to the Google Colab and read the file like this:

In [ ]:
data = pd.read_excel("/content/meap01_v4.xlsx")
data

,dcode,bcode,math4,read4,lunch,enroll,expend,exppp,lenroll,lexpend,lexppp
0,82160,48,68.5,57.4,17.31,364,1602988,4403.813,5.897154,14.28738,8.390226
1,50140,5223,74.0,46.8,23.63,474,2615864,5518.700,6.161207,14.77711,8.615897
2,82110,4094,87.3,56.4,30.77,403,1923443,4772.812,5.998937,14.46963,8.470691
3,82140,1888,47.3,50.9,11.90,294,1356769,4614.860,5.683580,14.12062,8.437037
4,82010,689,84.2,81.6,14.12,177,974155,5503.701,5.176150,13.78933,8.613176
...,...,...,...,...,...,...,...,...,...,...,...
1726,67055,5350,69.8,46.5,38.74,222,1036401,4668.473,5.402678,13.85126,8.448587
1727,47080,3037,86.7,81.7,13.06,222,1266669,5705.716,5.402678,14.05190,8.649224
1728,45040,2764,75.0,75.0,34.14,290,1831344,6314.979,5.669881,14.42056,8.750680
1729,7020,5784,50.0,57.1,34.99,483,991466,2052.725,6.180017,13.80694,7.626923
1730,82365,6420,70.4,64.8,36.34,344,2030546,5902.750,5.840641,14.52382,8.683173

# Reading data

For the lab, I am using the library but you should only use the Excel file provided in the MindTap.

In [1]:
%%capture

!pip install wooldridge

import wooldridge as woo

data = woo.data('401k')

In [3]:
data

           prate  mrate  totpart  totelg  age  totemp  sole   ltotemp
0      26.100000   0.21   1653.0  6322.0    8  8709.0     0  9.072112
1     100.000000   1.42    262.0   262.0    6   315.0     1  5.752573
2      97.599998   0.91    166.0   170.0   10   275.0     1  5.616771
3     100.000000   0.42    257.0   257.0    7   500.0     0  6.214608
4      82.500000   0.53    591.0   716.0   28   933.0     1  6.838405
...          ...    ...      ...     ...  ...     ...   ...       ...
1529   85.099998   0.33    553.0   650.0   24   907.0     0  6.810143
1530  100.000000   2.52    142.0   142.0   17   197.0     1  5.283204
1531  100.000000   2.27   1928.0  1928.0   35  2171.0     0  7.682943
1532  100.000000   0.58    166.0   166.0    8   931.0     1  6.836259
1533  100.000000   0.45   2179.0  2179.0   24  3187.0     0  8.066835

[1534 rows x 8 columns]

# Regression

In [4]:
import statsmodels.formula.api as smf

# Create the model
model = smf.ols('totpart ~ totelg', data)

# Fit the model
results = model.fit()

# Display regression results
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                totpart   R-squared:                       0.953
Model:                            OLS   Adj. R-squared:                  0.953
Method:                 Least Squares   F-statistic:                 3.091e+04
Date:                Fri, 13 Sep 2024   Prob (F-statistic):               0.00
Time:                        11:00:30   Log-Likelihood:                -12782.
No. Observations:                1534   AIC:                         2.557e+04
Df Residuals:                    1532   BIC:                         2.558e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -15.9342     26.848     -0.593      0.553     -68.597      36.729
totelg         0.8413      0.005    175.818      0.000       0.832       0.851
==============================================================================
Omnibus:                     2929.576   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         10508745.790
Skew:                         -13.731   Prob(JB):                         0.00
Kurtosis:                     407.548   Cond. No.                     5.86e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.86e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

# Reading Stata Files

## read_stata

Once the file is uploaded and the libraries you are going to use imported, you can read it into a DataFrame.

```python
data = pd.read_stata('file.dta')
```

Make sure the filename matches the uploaded file.

You can also reference the full Google Colab filesystem path if needed:

```
data = pd.read_stata('/content/file.dta')
```

For example, we can import a dta file of survey data downloaded from a website:

To read a dta file into a DataFrame:

```python
data = pd.read_stata('LFS-71M0001-E-2023-August_F1.dta')
```

Pandas will automatically convert the data into a DataFrame.

Here is the documentation for read_stata.
https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fpandas.pydata.org%2Fdocs%2Freference%2Fapi%2Fpandas.read_stata.html

## Labels or Values

When you are reading the dta files, you can indicate if you need the values(convert_categoricals = False) or the lables(convert_categoricals = True) for the categorical variables as below. The read_stata by default read the lables not the values.

```python
data = pd.read_stata('LFS-71M0001-E-2023-August_F1.dta', convert_categoricals=False)
```

In [24]:
data_stata_labels = pd.read_stata("/content/LFS-71M0001-E-2023-January_F1.dta")
data_stata_labels

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1,2023,January,"Employed, at work",Quebec,Montréal,45 to 49 years,NaN,Female,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,1312
1,2,2023,January,"Employed, at work",Saskatchewan,Other CMA or non-CMA,30 to 34 years,NaN,Female,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,91
2,3,2023,January,"Employed, at work",Newfoundland and Labrador,Other CMA or non-CMA,60 to 64 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, no childr...",NaN,136
3,4,2023,January,Not in labour force,Ontario,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,107
4,5,2023,January,"Employed, at work",Ontario,Other CMA or non-CMA,35 to 39 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Other families,NaN,242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108059,108060,2023,January,"Employed, absent from work",Manitoba,Winnipeg,50 to 54 years,NaN,Female,Separated,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,90
108060,108061,2023,January,Not in labour force,Prince Edward Island,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,39
108061,108062,2023,January,"Employed, at work",Quebec,Other CMA or non-CMA,50 to 54 years,NaN,Male,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,165
108062,108063,2023,January,Not in labour force,Ontario,Toronto,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,248
108063,108064,2023,January,Not in labour force,British Columbia,Vancouver,20 to 24 years,20 to 21 years,Female,"Single, never married",...,NaN,NaN,NaN,NaN,"Wanted work, reason - other personal or family...",NaN,Non-student,"Dual-earner couple, youngest child 0 to 17",NaN,340

In [13]:
data_stata_values = pd.read_stata('/content/LFS-71M0001-E-2023-January_F1.dta', convert_categoricals=False)
data_stata_values

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1,2023,1,1,24,2,7,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,1312
1,2,2023,1,1,47,0,4,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,91
2,3,2023,1,1,10,0,10,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5,NaN,136
3,4,2023,1,4,35,0,12,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,107
4,5,2023,1,1,35,0,5,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,18,NaN,242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108059,108060,2023,1,2,46,6,8,NaN,2,4,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,90
108060,108061,2023,1,4,11,0,12,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,39
108061,108062,2023,1,1,24,0,8,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,165
108062,108063,2023,1,4,35,4,12,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,248
108063,108064,2023,1,4,59,9,2,3.0,2,6,...,NaN,NaN,NaN,NaN,3.0,NaN,1.0,3,NaN,340

## Description

In [16]:
data_stata = pd.read_stata('/content/LFS-71M0001-E-2023-January_F1.dta', iterator=True)
data_stata.variable_labels()

{'REC_NUM': 'Order of record in file',
 'SURVYEAR': 'Survey year',
 'SURVMNTH': 'Survey month',
 'LFSSTAT': 'Labour force status',
 'PROV': 'Province',
 'CMA': 'Nine largest CMAs',
 'AGE_12': 'Five-year age group of respondent',
 'AGE_6': 'Age in 2 and 3 year groups, 15 to 29',
 'SEX': 'Sex of respondent',
 'MARSTAT': 'Marital status of respondent',
 'EDUC': 'Highest educational attainment',
 'MJH': 'Single or multiple jobholder',
 'EVERWORK': 'Not currently employed, worked in the past',
 'FTPTLAST': 'Full- or part-time status of last job',
 'COWMAIN': 'Class of worker, main job',
 'IMMIG': 'Immigration status',
 'NAICS_21': 'Industry of main job',
 'NOC_10': 'Occupation at main job',
 'NOC_43': 'Occupation at main job',
 'YABSENT': 'Reason of absence, full week',
 'WKSAWAY': 'Number of weeks absent from work',
 'PAYAWAY': 'Paid for time off, full-week absence only',
 'UHRSMAIN': 'Usual hours worked per week at main job',
 'AHRSMAIN': 'Actual hours worked per week at main job',
 'FTPTMAIN': 'Full- or part-time status at main or only job',
 'UTOTHRS': 'Usual hours worked per week at all jobs',
 'ATOTHRS': 'Actual hours worked per week at all jobs',
 'HRSAWAY': 'Hours away from work, part-week absence only',
 'YAWAY': 'Reason for part-week absence',
 'PAIDOT': 'Paid overtime hours in reference week',
 'UNPAIDOT': 'Unpaid overtime hours in reference week',
 'XTRAHRS': 'Number of overtime or extra hours worked',
 'WHYPT': 'Reason for part-time work',
 'TENURE': 'Job tenure with current employer (months)',
 'PREVTEN': 'Job tenure with previous employer (months)',
 'HRLYEARN': 'Usual hourly wages, employees only',
 'UNION': 'Union status, employees only',
 'PERMTEMP': 'Job permanency, employees only',
 'ESTSIZE': 'Establishment size',
 'FIRMSIZE': 'Firm size',
 'DURUNEMP': 'Duration of unemployment (weeks)',
 'FLOWUNEM': 'Flows into unemployment',
 'UNEMFTPT': 'Unemployed, type of job wanted',
 'WHYLEFTO': 'Reason for leaving job during previous year',
 'WHYLEFTN': 'Reason for leaving job during previous year',
 'DURJLESS': 'Duration of joblessness (months)',
 'AVAILABL': 'Availability during the reference week',
 'LKPUBAG': 'Unemployed, used public employment agency',
 'LKEMPLOY': 'Unemployed, checked with employers directly',
 'LKRELS': 'Unemployed, checked with friends or relatives',
 'LKATADS': 'Unemployed, looked at job ads',
 'LKANSADS': 'Unemployed, placed or answered ads',
 'LKOTHERN': 'Unemployed, other methods',
 'PRIORACT': 'Main activity before started looking for work',
 'YNOLOOK': 'Reason for not looking for work during the reference week',
 'TLOLOOK': 'Temporary layoff, looked for work during the last four weeks',
 'SCHOOLN': 'Current student status',
 'EFAMTYPE': 'Type of economic family',
 'AGYOWNK': 'Age of youngest child',
 'FINALWT': 'Standard final weight'}

## Type

In [18]:
data_stata_type = pd.read_stata('/content/LFS-71M0001-E-2023-January_F1.dta', preserve_dtypes=True)
data_stata_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108064 entries, 0 to 108063
Data columns (total 60 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   REC_NUM   108064 non-null  int32
 1   SURVYEAR  108064 non-null  int16
 2   SURVMNTH  108064 non-null  category
 3   LFSSTAT   108064 non-null  category
 4   PROV      108064 non-null  category
 5   CMA       108064 non-null  category
 6   AGE_12    108064 non-null  category
 7   AGE_6     20502 non-null   category
 8   SEX       108064 non-null  category
 9   MARSTAT   108064 non-null  category
 10  EDUC      108064 non-null  category
 11  MJH       63081 non-null   category
 12  EVERWORK  44983 non-null   category
 13  FTPTLAST  7621 non-null    category
 14  COWMAIN   70702 non-null   category
 15  IMMIG     108064 non-null  category
 16  NAICS_21  70702 non-null   category
 17  NOC_10    70702 non-null   category
 18  NOC_43    70702 non-null   category
 19  YABSENT   5097 non-null    category
 20  WKSAWAY   5097 non-null    float64
 21  PAYAWAY   4405 non-null    category
 22  UHRSMAIN  63081 non-null   float64
 23  AHRSMAIN  63081 non-null   float64
 24  FTPTMAIN  63081 non-null   category
 25  UTOTHRS   63081 non-null   float64
 26  ATOTHRS   63081 non-null   float64
 27  HRSAWAY   50335 non-null   float64
 28  YAWAY     6429 non-null    category
 29  PAIDOT    50335 non-null   float64
 30  UNPAIDOT  50335 non-null   float64
 31  XTRAHRS   50335 non-null   float64
 32  WHYPT     12071 non-null   category
 33  TENURE    63081 non-null   float64
 34  PREVTEN   7621 non-null    float64
 35  HRLYEARN  54289 non-null   float64
 36  UNION     54289 non-null   category
 37  PERMTEMP  54289 non-null   category
 38  ESTSIZE   54289 non-null   category
 39  FIRMSIZE  54289 non-null   category
 40  DURUNEMP  3512 non-null    float64
 41  FLOWUNEM  3660 non-null    category
 42  UNEMFTPT  3660 non-null    category
 43  WHYLEFTO  7621 non-null    category
 44  WHYLEFTN  7621 non-null    category
 45  DURJLESS  37965 non-null   float64
 46  AVAILABL  4032 non-null    category
 47  LKPUBAG   396 non-null     category
 48  LKEMPLOY  1457 non-null    category
 49  LKRELS    983 non-null     category
 50  LKATADS   2551 non-null    category
 51  LKANSADS  1366 non-null    category
 52  LKOTHERN  782 non-null     category
 53  PRIORACT  3293 non-null    category
 54  YNOLOOK   1379 non-null    category
 55  TLOLOOK   231 non-null     category
 56  SCHOOLN   80220 non-null   category
 57  EFAMTYPE  108064 non-null  category
 58  AGYOWNK   27839 non-null   category
 59  FINALWT   108064 non-null  int16
dtypes: category(43), float64(14), int16(2), int32(1)
memory usage: 16.8 MB

# Pandas

## shape

In [26]:
data_stata_labels.shape

(108064, 60)

## head

In [27]:
data_stata_labels.head()

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1,2023,January,"Employed, at work",Quebec,Montréal,45 to 49 years,NaN,Female,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,1312
1,2,2023,January,"Employed, at work",Saskatchewan,Other CMA or non-CMA,30 to 34 years,NaN,Female,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,91
2,3,2023,January,"Employed, at work",Newfoundland and Labrador,Other CMA or non-CMA,60 to 64 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, no childr...",NaN,136
3,4,2023,January,Not in labour force,Ontario,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,107
4,5,2023,January,"Employed, at work",Ontario,Other CMA or non-CMA,35 to 39 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Other families,NaN,242

## tail

In [28]:
data_stata_labels.tail()

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
108059,108060,2023,January,"Employed, absent from work",Manitoba,Winnipeg,50 to 54 years,NaN,Female,Separated,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,90
108060,108061,2023,January,Not in labour force,Prince Edward Island,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,39
108061,108062,2023,January,"Employed, at work",Quebec,Other CMA or non-CMA,50 to 54 years,NaN,Male,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,165
108062,108063,2023,January,Not in labour force,Ontario,Toronto,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,248
108063,108064,2023,January,Not in labour force,British Columbia,Vancouver,20 to 24 years,20 to 21 years,Female,"Single, never married",...,NaN,NaN,NaN,NaN,"Wanted work, reason - other personal or family...",NaN,Non-student,"Dual-earner couple, youngest child 0 to 17",NaN,340

## drop

In [30]:
data_drop = data_stata_labels.drop(columns=['SURVYEAR'])
data_drop

,REC_NUM,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,EDUC,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1,January,"Employed, at work",Quebec,Montréal,45 to 49 years,NaN,Female,"Single, never married",0 to 8 years,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,1312
1,2,January,"Employed, at work",Saskatchewan,Other CMA or non-CMA,30 to 34 years,NaN,Female,"Single, never married",Bachelor's degree,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,91
2,3,January,"Employed, at work",Newfoundland and Labrador,Other CMA or non-CMA,60 to 64 years,NaN,Male,Married,Some high school,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, no childr...",NaN,136
3,4,January,Not in labour force,Ontario,Other CMA or non-CMA,70 and over,NaN,Female,Married,Postsecondary certificate or diploma,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,107
4,5,January,"Employed, at work",Ontario,Other CMA or non-CMA,35 to 39 years,NaN,Male,Married,High school graduate,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Other families,NaN,242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108059,108060,January,"Employed, absent from work",Manitoba,Winnipeg,50 to 54 years,NaN,Female,Separated,0 to 8 years,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,90
108060,108061,January,Not in labour force,Prince Edward Island,Other CMA or non-CMA,70 and over,NaN,Female,Married,Some high school,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,39
108061,108062,January,"Employed, at work",Quebec,Other CMA or non-CMA,50 to 54 years,NaN,Male,"Single, never married",Some high school,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,165
108062,108063,January,Not in labour force,Ontario,Toronto,70 and over,NaN,Female,Married,Postsecondary certificate or diploma,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,248
108063,108064,January,Not in labour force,British Columbia,Vancouver,20 to 24 years,20 to 21 years,Female,"Single, never married",Some postsecondary,...,NaN,NaN,NaN,NaN,"Wanted work, reason - other personal or family...",NaN,Non-student,"Dual-earner couple, youngest child 0 to 17",NaN,340

## new column

In [33]:
data_stata_labels['Year'] = data_stata_labels['SURVYEAR']+1
data_stata_labels

#lab3valuecount

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT,Year
0,1,2023,January,"Employed, at work",Quebec,Montréal,45 to 49 years,NaN,Female,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,1312,2024
1,2,2023,January,"Employed, at work",Saskatchewan,Other CMA or non-CMA,30 to 34 years,NaN,Female,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,91,2024
2,3,2023,January,"Employed, at work",Newfoundland and Labrador,Other CMA or non-CMA,60 to 64 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, no childr...",NaN,136,2024
3,4,2023,January,Not in labour force,Ontario,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,107,2024
4,5,2023,January,"Employed, at work",Ontario,Other CMA or non-CMA,35 to 39 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,Non-student,Other families,NaN,242,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108059,108060,2023,January,"Employed, absent from work",Manitoba,Winnipeg,50 to 54 years,NaN,Female,Separated,...,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,90,2024
108060,108061,2023,January,Not in labour force,Prince Edward Island,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,39,2024
108061,108062,2023,January,"Employed, at work",Quebec,Other CMA or non-CMA,50 to 54 years,NaN,Male,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,165,2024
108062,108063,2023,January,Not in labour force,Ontario,Toronto,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,248,2024
108063,108064,2023,January,Not in labour force,British Columbia,Vancouver,20 to 24 years,20 to 21 years,Female,"Single, never married",...,NaN,NaN,NaN,"Wanted work, reason - other personal or family...",NaN,Non-student,"Dual-earner couple, youngest child 0 to 17",NaN,340,2024